name: Release SK8-PAD

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_id: linux_windows
          - os: macos-latest
            build_id: macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: src/sk8-pad/go.sum

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libxf86vm-dev

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --config ../../.goreleaser.yaml --filter.id=${{ matrix.build_id }}
          workdir: src/sk8-pad
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
